/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.nlu.cnpm.cnpm;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF5dkREatQ5x1k= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF5dkREatQ5x1k= >>
// ----------- >>
public class Controller {
    // ----------- << attribute.annotations@AAAAAAF5dk4UqdaXCK8= >>
    // ----------- >>
    private PostActivity ;

    // ----------- << attribute.annotations@AAAAAAF5dk3qe9V+IPY= >>
    // ----------- >>
    private PostActivity ;

    // ----------- << attribute.annotations@AAAAAAF5dk4zTNcb8t0= >>
    // ----------- >>
    private Post ;

    public PostActivity get() {
        return ;
    }

    public PostActivity get() {
        return ;
    }

    public Post get() {
        return ;
    }

    public void set(PostActivity ) {
        this. = ;
    }

    public void set(PostActivity ) {
        this. = ;
    }

    public void set(Post ) {
        this. = ;
    }

    public void link(PostActivity _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(PostActivity _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Post _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    /**
    * @param String text 
    * @param List listPicture 
    * @param List listVideo
    */

    // ----------- << method.annotations@AAAAAAF5dkh0qdSsNig= >>
    // ----------- >>
    public boolean post(void String text, void List listPicture, void List listVideo) {
    // ----------- << method.body@AAAAAAF5dkh0qdSsNig= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF5dkREatQ5x1k= >>
// ----------- >>
}