/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.nlu.cnpm.cnpm;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF5dkQt/tQPk6k= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF5dkQt/tQPk6k= >>
// ----------- >>
public class Database {
    // ----------- << attribute.annotations@AAAAAAF5dk5KaNfE2V0= >>
    // ----------- >>
    private Post ;

    public Post get() {
        return ;
    }

    public void set(Post ) {
        this. = ;
    }

    public void link(Post _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    /**
    * @param Post p
    */

    // ----------- << method.annotations@AAAAAAF5dkwZXtTKMLM= >>
    // ----------- >>
    public boolean insertPost(void Post p) {
    // ----------- << method.body@AAAAAAF5dkwZXtTKMLM= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF5dkQt/tQPk6k= >>
// ----------- >>
}