/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.nlu.cnpm.cnpm;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF5dkNnptOOcIc= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF5dkNnptOOcIc= >>
// ----------- >>
public class MainView {
    // ----------- << attribute.annotations@AAAAAAF5dk4L/9ZV3VQ= >>
    // ----------- >>
    private PostActivity ;

    // ----------- << attribute.annotations@AAAAAAF5dk2jG9To7oU= >>
    // ----------- >>
    private PostActivity ;

    public PostActivity get() {
        return ;
    }

    public PostActivity get() {
        return ;
    }

    public void set(PostActivity ) {
        this. = ;
    }

    public void set(PostActivity ) {
        this. = ;
    }

    public void link(PostActivity _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(PostActivity _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAF5dkTErtRqpMo= >>
    // ----------- >>
    public void createPost() {
    // ----------- << method.body@AAAAAAF5dkTErtRqpMo= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF5dkNnptOOcIc= >>
// ----------- >>
}