/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.nlu.cnpm.cnpm;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF5dkOMGdO5yE4= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF5dkOMGdO5yE4= >>
// ----------- >>
public class PostActivity {
    // ----------- << attribute.annotations@AAAAAAF5dk4L/tZUQng= >>
    // ----------- >>
    private MainView ;

    // ----------- << attribute.annotations@AAAAAAF5dk2jHNTpCv8= >>
    // ----------- >>
    private MainView ;

    // ----------- << attribute.annotations@AAAAAAF5dk4UqdaYj74= >>
    // ----------- >>
    private Controller ;

    // ----------- << attribute.annotations@AAAAAAF5dk3qe9V9tN4= >>
    // ----------- >>
    private Controller ;

    public MainView get() {
        return ;
    }

    public MainView get() {
        return ;
    }

    public Controller get() {
        return ;
    }

    public Controller get() {
        return ;
    }

    public void set(MainView ) {
        this. = ;
    }

    public void set(MainView ) {
        this. = ;
    }

    public void set(Controller ) {
        this. = ;
    }

    public void set(Controller ) {
        this. = ;
    }

    public void link(MainView _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(MainView _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Controller _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Controller _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAF5dkVHxdR0biY= >>
    // ----------- >>
    public void show() {
    // ----------- << method.body@AAAAAAF5dkVHxdR0biY= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF5dkcd1dSPV7c= >>
    // ----------- >>
    public String getText() {
    // ----------- << method.body@AAAAAAF5dkcd1dSPV7c= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF5dkYXVdR7tRo= >>
    // ----------- >>
    public List addPicture() {
    // ----------- << method.body@AAAAAAF5dkYXVdR7tRo= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF5dka7BdSCNyo= >>
    // ----------- >>
    public List addVideo() {
    // ----------- << method.body@AAAAAAF5dka7BdSCNyo= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF5dkdJitSaltY= >>
    // ----------- >>
    public String post() {
    // ----------- << method.body@AAAAAAF5dkdJitSaltY= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF5dkOMGdO5yE4= >>
// ----------- >>
}