/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.nlu.cnpm.cnpm;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF5dkQNedPlyX8= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF5dkQNedPlyX8= >>
// ----------- >>
public class Post {
    // ----------- << attribute.annotations@AAAAAAF5dk5KaNfFG4M= >>
    // ----------- >>
    private Database ;

    // ----------- << attribute.annotations@AAAAAAF5dk4zTNcaLBo= >>
    // ----------- >>
    private Controller ;

    public Database get() {
        return ;
    }

    public Controller get() {
        return ;
    }

    public void set(Database ) {
        this. = ;
    }

    public void set(Controller ) {
        this. = ;
    }

    public void link(Database _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Controller _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    /**
    * @param String text 
    * @param List listPicture 
    * @param List listVideo 
    * @param User user
    */

    // ----------- << method.annotations@AAAAAAF5dkgn19Sk3qw= >>
    // ----------- >>
    public boolean createPost(void String text, void List listPicture, void List listVideo, void User user) {
    // ----------- << method.body@AAAAAAF5dkgn19Sk3qw= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF5dkQNedPlyX8= >>
// ----------- >>
}